name: elapro
description: Uma ferramenta de gestÃ£o para mulheres microempreendedoras.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  intl: ^0.19.0
  flutter_svg: ^2.0.9
  phosphor_flutter: ^2.1.0
  mobx: ^2.3.0
  flutter_mobx: ^2.2.0
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0
  url_launcher: ^6.2.5
  flutter_contacts: ^1.1.9+2
  permission_handler: ^12.0.1
  mask_text_input_formatter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  mobx_codegen: ^2.6.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
